apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: load-tester-hpa
  namespace: load-tester
  labels:
    app: load-tester
    environment: gke
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: load-tester
  minReplicas: 1
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 3
        periodSeconds: 60
      selectPolicy: Max