apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: load-tester

resources:
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/job.yaml
- namespace.yaml
- service-account.yaml
- hpa.yaml

patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml

images:
- name: load-tester
  newName: gcr.io/<PROJECT_ID>/load-tester
  newTag: latest

commonLabels:
  environment: gke
  cloud-provider: gcp
  
configMapGenerator:
- name: load-tester-config-gke
  literals:
  - concurrent-users=25
  - test-duration=1800
  - streaming-url=https://example.com/stream
  - prometheus-enabled=true
  - otel-enabled=true