apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: load-tester

resources:
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/job.yaml
- namespace.yaml
- service-account.yaml
- hpa.yaml

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml
- storage-patch.yaml

images:
- name: load-tester
  newName: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/load-tester
  newTag: latest

commonLabels:
  environment: aws-eks
  
configMapGenerator:
- name: load-tester-config-aws
  literals:
  - concurrent-users=20
  - test-duration=1800
  - streaming-url=https://example.com/stream
  - prometheus-enabled=true
  - otel-enabled=true