apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: load-tester

resources:
- ../../base/deployment.yaml
- ../../base/service.yaml
- ../../base/job.yaml
- namespace.yaml
- service-account.yaml
- hpa.yaml

patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml

images:
- name: load-tester
  newName: <REGISTRY_NAME>.azurecr.io/load-tester
  newTag: latest

commonLabels:
  environment: aks
  cloud-provider: azure
  
configMapGenerator:
- name: load-tester-config-aks
  literals:
  - concurrent-users=20
  - test-duration=1800
  - streaming-url=https://example.com/stream
  - prometheus-enabled=true
  - otel-enabled=true