apiVersion: v1
kind: ServiceAccount
metadata:
  name: load-tester-sa
  namespace: load-tester
  annotations:
    # Replace with your actual Azure identity client ID
    azure.workload.identity/client-id: "<CLIENT_ID>"
  labels:
    app: load-tester
    environment: aks
    azure.workload.identity/use: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: load-tester-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: load-tester-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: load-tester-role
subjects:
- kind: ServiceAccount
  name: load-tester-sa
  namespace: load-tester