apiVersion: v1
kind: Service
metadata:
  name: load-tester-service
  labels:
    app: load-tester
spec:
  selector:
    app: load-tester
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: load-tester-metrics
  labels:
    app: load-tester
    service: metrics
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: load-tester
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  type: ClusterIP